default: &default
  adapter: postgresql
  encoding: unicode
  username: development
  password: development
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails-react-exercise_development

test:
  <<: *default
  database: rails-react-exercise_test

production:
  <<: *default
  database: rails-react-exercise_production
  username: rails-react-exercise
  password: <%= ENV['RAILS-REACT-EXERCISE_DATABASE_PASSWORD'] %>
